---
AWSTemplateFormatVersion: 2010-09-09
Description: Cloud Formation to EC2

Parameters:
  ImageId:
   Description: Lista ImageId
   Type: List<AWS::EC2::Image::Id>
   Default: 
  InstanceType:
   Description: lista Instance
   Type: List<AWS::EC2::Instance::Id>
   Default: 

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType




 
 
























